server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Siempre revalidar HTML/JS/CSS/datos para que los cambios se vean sin caché vieja
    location ~* \.(?:html|js|css|json)$ {
        add_header Cache-Control "no-cache";
    }
}
