// Datos generados a partir de las carpetas Hombre/ y Mujer/ y del catálogo Excel
const PRODUCTS = [
  {
    "id": 1,
    "name": "9AM",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/9AM.webp",
    "file": "9AM.webp",
    "brand": "Afnan",
    "priceMenudeo": 590,
    "priceMayoreo": 690
  },
  {
    "id": 2,
    "name": "9PM Rebel",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/9PM Rebel.jpeg",
    "file": "9PM Rebel.jpeg",
    "brand": "Afnan",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 3,
    "name": "9PM",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/9PM.webp",
    "file": "9PM.webp",
    "brand": "Afnan",
    "priceMenudeo": 590,
    "priceMayoreo": 690
  },
  {
    "id": 4,
    "name": "Aether",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Aether.webp",
    "file": "Aether.webp",
    "brand": "French Avenue",
    "priceMenudeo": 900,
    "priceMayoreo": 1090
  },
  {
    "id": 5,
    "name": "Al Noble Ameer",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Al Noble Ameer.jpg",
    "file": "Al Noble Ameer.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 480,
    "priceMayoreo": 590
  },
  {
    "id": 6,
    "name": "Amber Oud Aqua Dubai",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Amber Oud Aqua Dubai.webp",
    "file": "Amber Oud Aqua Dubai.webp",
    "brand": "Al Haramain",
    "priceMenudeo": 1090,
    "priceMayoreo": 1290
  },
  {
    "id": 7,
    "name": "Amber Oud Dubai Night",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Amber Oud Dubai Night.webp",
    "file": "Amber Oud Dubai Night.webp",
    "brand": "Al Haramain",
    "priceMenudeo": 1040,
    "priceMayoreo": 1190
  },
  {
    "id": 8,
    "name": "Amber Oud Gold Edition",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Amber Oud Gold Edition.webp",
    "file": "Amber Oud Gold Edition.webp",
    "brand": "Al Haramain",
    "priceMenudeo": 1040,
    "priceMayoreo": 1190
  },
  {
    "id": 9,
    "name": "Amber Oud Ruby Edition",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Amber Oud Ruby Edition.webp",
    "file": "Amber Oud Ruby Edition.webp",
    "brand": "Al Haramain",
    "priceMenudeo": 1040,
    "priceMayoreo": 1190
  },
  {
    "id": 10,
    "name": "Amber Rouge",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Amber Rouge.jpeg",
    "file": "Amber Rouge.jpeg",
    "brand": "Orientica",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 11,
    "name": "Amethyst",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Amethyst.webp",
    "file": "Amethyst.webp",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 750
  },
  {
    "id": 12,
    "name": "Aoud",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Aoud.webp",
    "file": "Aoud.webp",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 13,
    "name": "Art of Universe",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Art of Universe.webp",
    "file": "Art of Universe.webp",
    "brand": "Lattafa",
    "priceMenudeo": 950,
    "priceMayoreo": 1090
  },
  {
    "id": 14,
    "name": "Asad Bourbon",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Asad Bourbon.jpg",
    "file": "Asad Bourbon.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 690,
    "priceMayoreo": 890
  },
  {
    "id": 15,
    "name": "Asad Zanzibar",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Asad Zanzibar.jpg",
    "file": "Asad Zanzibar.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 540,
    "priceMayoreo": 690
  },
  {
    "id": 16,
    "name": "Asad",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Asad.webp",
    "file": "Asad.webp",
    "brand": "Lattafa",
    "priceMenudeo": 540,
    "priceMayoreo": 590
  },
  {
    "id": 17,
    "name": "Azzure Aoud",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Azzure Aoud.jpg",
    "file": "Azzure Aoud.jpg",
    "brand": "French Avenue",
    "priceMenudeo": 900,
    "priceMayoreo": 1090
  },
  {
    "id": 18,
    "name": "Boston",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Boston.jpg",
    "file": "Boston.jpg",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 19,
    "name": "Bright Peach",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Bright Peach.webp",
    "file": "Bright Peach.webp",
    "brand": "Maison Alhambra",
    "priceMenudeo": 500,
    "priceMayoreo": 650
  },
  {
    "id": 20,
    "name": "Chocolate",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Chocolate.jpg",
    "file": "Chocolate.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 21,
    "name": "Club de Nuit Iconic",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Club de Nuit Iconic.jpg",
    "file": "Club de Nuit Iconic.jpg",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 22,
    "name": "Club de Nuit Imperiale",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Club de Nuit Imperiale.webp",
    "file": "Club de Nuit Imperiale.webp",
    "brand": "Armaf",
    "priceMenudeo": 640,
    "priceMayoreo": 890
  },
  {
    "id": 23,
    "name": "Club de Nuit Intense Man",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Club de Nuit Intense Man.jpg",
    "file": "Club de Nuit Intense Man.jpg",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 690
  },
  {
    "id": 24,
    "name": "Club de Nuit Intense Parfum",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Club de Nuit Intense Parfum.jpg",
    "file": "Club de Nuit Intense Parfum.jpg",
    "brand": "Armaf",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 25,
    "name": "Club de Nuit Milestone",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Club de Nuit Milestone.jpg",
    "file": "Club de Nuit Milestone.jpg",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 930
  },
  {
    "id": 26,
    "name": "Club de Nuit Sillage",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Club de Nuit Sillage.jpg",
    "file": "Club de Nuit Sillage.jpg",
    "brand": "Armaf",
    "priceMenudeo": 720,
    "priceMayoreo": 890
  },
  {
    "id": 27,
    "name": "Club de Nuit Urban Man Elixir",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Club de Nuit Urban Man Elixir.webp",
    "file": "Club de Nuit Urban Man Elixir.webp",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 28,
    "name": "Dom",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Dom.jpg",
    "file": "Dom.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 29,
    "name": "Double Bleu",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Double Bleu.jpg",
    "file": "Double Bleu.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 30,
    "name": "Essence",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Essence.jpg",
    "file": "Essence.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1090,
    "priceMayoreo": 1190
  },
  {
    "id": 31,
    "name": "Full House",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Full House.webp",
    "file": "Full House.webp",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 32,
    "name": "Glacier Bold",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Glacier Bold.jpg",
    "file": "Glacier Bold.jpg",
    "brand": "Maison Alhambra",
    "priceMenudeo": 600,
    "priceMayoreo": 750
  },
  {
    "id": 33,
    "name": "Glacier Le Noir",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Glacier Le Noir.jpg",
    "file": "Glacier Le Noir.jpg",
    "brand": "Maison Alhambra",
    "priceMenudeo": 600,
    "priceMayoreo": 750
  },
  {
    "id": 34,
    "name": "Gold",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Gold.jpg",
    "file": "Gold.jpg",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 35,
    "name": "Hawas Atlantis",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Atlantis.jpg",
    "file": "Hawas Atlantis.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 1290,
    "priceMayoreo": 1390
  },
  {
    "id": 36,
    "name": "Hawas Black",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Black.jpg",
    "file": "Hawas Black.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 890,
    "priceMayoreo": 1150
  },
  {
    "id": 37,
    "name": "Hawas Elixir",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Elixir.jpg",
    "file": "Hawas Elixir.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 890,
    "priceMayoreo": 1190
  },
  {
    "id": 38,
    "name": "Hawas Fire",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Fire.jpg",
    "file": "Hawas Fire.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 990,
    "priceMayoreo": 1290
  },
  {
    "id": 39,
    "name": "Hawas for Him",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas for Him.jpg",
    "file": "Hawas for Him.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 640,
    "priceMayoreo": 790
  },
  {
    "id": 40,
    "name": "Hawas Ice",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Ice.jpg",
    "file": "Hawas Ice.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 41,
    "name": "Hawas Kobra",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Kobra.jpg",
    "file": "Hawas Kobra.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 990,
    "priceMayoreo": 1290
  },
  {
    "id": 42,
    "name": "Hawas Malibu",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Malibu.jpg",
    "file": "Hawas Malibu.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 990,
    "priceMayoreo": 1290
  },
  {
    "id": 43,
    "name": "Hawas Verde",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Verde.jpg",
    "file": "Hawas Verde.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 44,
    "name": "Hawas Viper",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Hawas Viper.jpg",
    "file": "Hawas Viper.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 1290,
    "priceMayoreo": 1390
  },
  {
    "id": 45,
    "name": "Honor & Glory",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Honor & Glory.webp",
    "file": "Honor & Glory.webp",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 46,
    "name": "Jo Milano King",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Jo Milano King.jpg",
    "file": "Jo Milano King.jpg",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 47,
    "name": "Khamrah Dukhan",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Khamrah Dukhan.webp",
    "file": "Khamrah Dukhan.webp",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 48,
    "name": "Khamrah Qahwah",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Khamrah Qahwah.png",
    "file": "Khamrah Qahwah.png",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 690
  },
  {
    "id": 49,
    "name": "Khamrah",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Khamrah.jpg",
    "file": "Khamrah.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 580,
    "priceMayoreo": 690
  },
  {
    "id": 50,
    "name": "King Gold Edition",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/King Gold Edition.jpg",
    "file": "King Gold Edition.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1290,
    "priceMayoreo": 1440
  },
  {
    "id": 51,
    "name": "King Parfum",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/King Parfum.webp",
    "file": "King Parfum.webp",
    "brand": "Bharara",
    "priceMenudeo": 1350,
    "priceMayoreo": 1490
  },
  {
    "id": 52,
    "name": "King Soleil",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/King Soleil.jpg",
    "file": "King Soleil.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1690,
    "priceMayoreo": 1890
  },
  {
    "id": 53,
    "name": "King",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/King.webp",
    "file": "King.webp",
    "brand": "Bharara",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 54,
    "name": "Liam",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Liam.jpg",
    "file": "Liam.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 720
  },
  {
    "id": 55,
    "name": "Liquid Brun",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Liquid Brun.jpg",
    "file": "Liquid Brun.jpg",
    "brand": "French Avenue",
    "priceMenudeo": 900,
    "priceMayoreo": 1090
  },
  {
    "id": 56,
    "name": "Lovely Cherie",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Lovely Cherie.webp",
    "file": "Lovely Cherie.webp",
    "brand": "Maison Alhambra",
    "priceMenudeo": 500,
    "priceMayoreo": 650
  },
  {
    "id": 57,
    "name": "Maahir Black",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Maahir Black.jpg",
    "file": "Maahir Black.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 58,
    "name": "Maahir Gold",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Maahir Gold.jpg",
    "file": "Maahir Gold.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 750
  },
  {
    "id": 59,
    "name": "Maahir Silver",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Maahir Silver.webp",
    "file": "Maahir Silver.webp",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 750
  },
  {
    "id": 60,
    "name": "Mayar Cherry",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Mayar Cherry.webp",
    "file": "Mayar Cherry.webp",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 61,
    "name": "Mayar",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Mayar.jpg",
    "file": "Mayar.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 62,
    "name": "Nebras",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Nebras.jpg",
    "file": "Nebras.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 760,
    "priceMayoreo": 890
  },
  {
    "id": 63,
    "name": "Niche",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Niche.jpg",
    "file": "Niche.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 64,
    "name": "Nitro Black",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Nitro Black.webp",
    "file": "Nitro Black.webp",
    "brand": "Dumont",
    "priceMenudeo": 800,
    "priceMayoreo": 950
  },
  {
    "id": 65,
    "name": "Nitro Blue",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Nitro Blue.webp",
    "file": "Nitro Blue.webp",
    "brand": "Dumont",
    "priceMenudeo": 800,
    "priceMayoreo": 950
  },
  {
    "id": 66,
    "name": "Nitro Red Intensely",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Nitro Red Intensely.jpg",
    "file": "Nitro Red Intensely.jpg",
    "brand": "Dumont",
    "priceMenudeo": 800,
    "priceMayoreo": 950
  },
  {
    "id": 67,
    "name": "Nitro Red",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Nitro Red.jpg",
    "file": "Nitro Red.jpg",
    "brand": "Dumont",
    "priceMenudeo": 640,
    "priceMayoreo": 750
  },
  {
    "id": 68,
    "name": "Nitro White",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Nitro White.jpg",
    "file": "Nitro White.jpg",
    "brand": "Dumont",
    "priceMenudeo": 750,
    "priceMayoreo": 950
  },
  {
    "id": 69,
    "name": "Odyssey Aqua",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Aqua.jpg",
    "file": "Odyssey Aqua.jpg",
    "brand": "Armaf",
    "priceMenudeo": 690,
    "priceMayoreo": 890
  },
  {
    "id": 70,
    "name": "Odyssey Artisto",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Artisto.webp",
    "file": "Odyssey Artisto.webp",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 71,
    "name": "Odyssey Dubai Chocolat",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Dubai Chocolat.jpg",
    "file": "Odyssey Dubai Chocolat.jpg",
    "brand": "Armaf",
    "priceMenudeo": 680,
    "priceMayoreo": 890
  },
  {
    "id": 72,
    "name": "Odyssey Go Mango",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Go Mango.jpg",
    "file": "Odyssey Go Mango.jpg",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 73,
    "name": "Odyssey Homme White",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Homme White.webp",
    "file": "Odyssey Homme White.webp",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 74,
    "name": "Odyssey Homme",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Homme.jpg",
    "file": "Odyssey Homme.jpg",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 75,
    "name": "Odyssey Limoni",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Limoni.jpg",
    "file": "Odyssey Limoni.jpg",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 76,
    "name": "Odyssey Mandarin Sky Elixir",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Mandarin Sky Elixir.webp",
    "file": "Odyssey Mandarin Sky Elixir.webp",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 77,
    "name": "Odyssey Mandarin Sky",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Mandarin Sky.webp",
    "file": "Odyssey Mandarin Sky.webp",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 78,
    "name": "Odyssey Marshmallow",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Marshmallow.jpg",
    "file": "Odyssey Marshmallow.jpg",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 79,
    "name": "Odyssey Mega",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Mega.webp",
    "file": "Odyssey Mega.webp",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 80,
    "name": "Odyssey Spectra",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Spectra.webp",
    "file": "Odyssey Spectra.webp",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 81,
    "name": "Odyssey Tyrant",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Odyssey Tyrant.jpg",
    "file": "Odyssey Tyrant.jpg",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 82,
    "name": "Opal",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Opal.jpg",
    "file": "Opal.jpg",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 83,
    "name": "Oud for Glory",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Oud for Glory.jpg",
    "file": "Oud for Glory.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 84,
    "name": "Oud Saffron",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Oud Saffron.jpg",
    "file": "Oud Saffron.jpg",
    "brand": "Orientica",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 85,
    "name": "Oud",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Oud.webp",
    "file": "Oud.webp",
    "brand": "Armaf",
    "priceMenudeo": 1290,
    "priceMayoreo": 1390
  },
  {
    "id": 86,
    "name": "Pisa",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Pisa.jpg",
    "file": "Pisa.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 790,
    "priceMayoreo": 950
  },
  {
    "id": 87,
    "name": "Porto Neroli",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Porto Neroli.webp",
    "file": "Porto Neroli.webp",
    "brand": "Maison Alhambra",
    "priceMenudeo": 500,
    "priceMayoreo": 650
  },
  {
    "id": 88,
    "name": "Precieux",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Precieux.webp",
    "file": "Precieux.webp",
    "brand": "Armaf",
    "priceMenudeo": 950,
    "priceMayoreo": 1290
  },
  {
    "id": 89,
    "name": "Qaed Al Fursan Black",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Qaed Al Fursan Black.jpg",
    "file": "Qaed Al Fursan Black.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 490,
    "priceMayoreo": 590
  },
  {
    "id": 90,
    "name": "Qaed Al Fursan White",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Qaed Al Fursan White.jpg",
    "file": "Qaed Al Fursan White.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 490,
    "priceMayoreo": 650
  },
  {
    "id": 91,
    "name": "Revolution",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Revolution.jpg",
    "file": "Revolution.jpg",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 92,
    "name": "Rome Pour Homme",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Rome Pour Homme.webp",
    "file": "Rome Pour Homme.webp",
    "brand": "MP",
    "priceMenudeo": 760,
    "priceMayoreo": 990
  },
  {
    "id": 93,
    "name": "Rouge",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Rouge.jpg",
    "file": "Rouge.jpg",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 94,
    "name": "Royal Amber",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Royal Amber.jpg",
    "file": "Royal Amber.jpg",
    "brand": "Orientica",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 95,
    "name": "Royal Bleu",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Royal Bleu.jpg",
    "file": "Royal Bleu.jpg",
    "brand": "Orientica",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 96,
    "name": "Sakeena",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Sakeena.jpg",
    "file": "Sakeena.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 97,
    "name": "Spectre",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Spectre.jpg",
    "file": "Spectre.jpg",
    "brand": "French Avenue",
    "priceMenudeo": 870,
    "priceMayoreo": 990
  },
  {
    "id": 98,
    "name": "Sublime",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Sublime.jpg",
    "file": "Sublime.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 750
  },
  {
    "id": 99,
    "name": "Supremacy Gold",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Supremacy Gold.jpg",
    "file": "Supremacy Gold.jpg",
    "brand": "Afnan",
    "priceMenudeo": 600,
    "priceMayoreo": 750
  },
  {
    "id": 100,
    "name": "Supremacy Not Only",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Supremacy Not Only.jpg",
    "file": "Supremacy Not Only.jpg",
    "brand": "Afnan",
    "priceMenudeo": 600,
    "priceMayoreo": 790
  },
  {
    "id": 101,
    "name": "Teriaq Intense",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Teriaq Intense.webp",
    "file": "Teriaq Intense.webp",
    "brand": "Lattafa",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 102,
    "name": "Teriaq",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Teriaq.jpg",
    "file": "Teriaq.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 103,
    "name": "The Kingdom",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/The Kingdom.webp",
    "file": "The Kingdom.webp",
    "brand": "Lattafa",
    "priceMenudeo": 630,
    "priceMayoreo": 750
  },
  {
    "id": 104,
    "name": "Tobacco Touch",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Tobacco Touch.jpg",
    "file": "Tobacco Touch.jpg",
    "brand": "Maison Alhambra",
    "priceMenudeo": 500,
    "priceMayoreo": 650
  },
  {
    "id": 105,
    "name": "Velvet Gold",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Velvet Gold.jpeg",
    "file": "Velvet Gold.jpeg",
    "brand": "Orientica",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 106,
    "name": "Viking Beirut",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Viking Beirut.webp",
    "file": "Viking Beirut.webp",
    "brand": "Bharara",
    "priceMenudeo": 1150,
    "priceMayoreo": 1250
  },
  {
    "id": 107,
    "name": "Viking Cairo",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Viking Cairo.webp",
    "file": "Viking Cairo.webp",
    "brand": "Bharara",
    "priceMenudeo": 1150,
    "priceMayoreo": 1250
  },
  {
    "id": 108,
    "name": "Viking Dubai",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Viking Dubai.webp",
    "file": "Viking Dubai.webp",
    "brand": "Bharara",
    "priceMenudeo": 1150,
    "priceMayoreo": 1250
  },
  {
    "id": 109,
    "name": "Viking Kashmir",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Viking Kashmir.webp",
    "file": "Viking Kashmir.webp",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1400
  },
  {
    "id": 110,
    "name": "Viking Rio",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Viking Rio.jpg",
    "file": "Viking Rio.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1150,
    "priceMayoreo": 1250
  },
  {
    "id": 111,
    "name": "Vintage Radio",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Vintage Radio.jpg",
    "file": "Vintage Radio.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 112,
    "name": "Wilcard",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Wilcard.jpg",
    "file": "Wilcard.jpg",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 113,
    "name": "Wild One",
    "gender": "Hombre",
    "line": "Arabes",
    "image": "../Hombre/Arabes/Wild One.jpg",
    "file": "Wild One.jpg",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 114,
    "name": "212 Heroes (H)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/212 Heroes (H).jpg",
    "file": "212 Heroes (H).jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1590,
    "priceMayoreo": 1680
  },
  {
    "id": 115,
    "name": "212 Men NYC",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/212 Men NYC.jpg",
    "file": "212 Men NYC.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1490,
    "priceMayoreo": 1590
  },
  {
    "id": 116,
    "name": "212 Men Sexy",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/212 Men Sexy.webp",
    "file": "212 Men Sexy.webp",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1590,
    "priceMayoreo": 1790
  },
  {
    "id": 117,
    "name": "212 VIP Black",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/212 VIP Black.jpg",
    "file": "212 VIP Black.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1590,
    "priceMayoreo": 1790
  },
  {
    "id": 118,
    "name": "212 VIP Men",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/212 VIP Men.webp",
    "file": "212 VIP Men.webp",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1490,
    "priceMayoreo": 1650
  },
  {
    "id": 119,
    "name": "360 (H)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/360 (H).webp",
    "file": "360 (H).webp",
    "brand": "Perry Ellis",
    "priceMenudeo": 560,
    "priceMayoreo": 690
  },
  {
    "id": 120,
    "name": "Acqua di Giò EDP",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Acqua di Giò EDP.jpg",
    "file": "Acqua di Giò EDP.jpg",
    "brand": "Armani",
    "priceMenudeo": 1790,
    "priceMayoreo": 1890
  },
  {
    "id": 121,
    "name": "Acqua di Giò EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Acqua di Giò EDT.webp",
    "file": "Acqua di Giò EDT.webp",
    "brand": "Armani",
    "priceMenudeo": 1490,
    "priceMayoreo": 1690
  },
  {
    "id": 122,
    "name": "Acqua di Giò Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Acqua di Giò Parfum.jpg",
    "file": "Acqua di Giò Parfum.jpg",
    "brand": "Armani",
    "priceMenudeo": 2290,
    "priceMayoreo": 2480
  },
  {
    "id": 123,
    "name": "Acqua di Giò Profondo Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Acqua di Giò Profondo Parfum.jpg",
    "file": "Acqua di Giò Profondo Parfum.jpg",
    "brand": "Armani",
    "priceMenudeo": 2390,
    "priceMayoreo": 2690
  },
  {
    "id": 124,
    "name": "Acqua di Giò Profondo",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Acqua di Giò Profondo.jpg",
    "file": "Acqua di Giò Profondo.jpg",
    "brand": "Armani",
    "priceMenudeo": 2290,
    "priceMayoreo": 2490
  },
  {
    "id": 125,
    "name": "Bad Boy Cobalt Elixir",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Bad Boy Cobalt Elixir.jpg",
    "file": "Bad Boy Cobalt Elixir.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1790,
    "priceMayoreo": 2090
  },
  {
    "id": 126,
    "name": "Bad Boy Cobalt",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Bad Boy Cobalt.jpg",
    "file": "Bad Boy Cobalt.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1690,
    "priceMayoreo": 1890
  },
  {
    "id": 127,
    "name": "Bad Boy Extreme",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Bad Boy Extreme.jpg",
    "file": "Bad Boy Extreme.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1990,
    "priceMayoreo": 2090
  },
  {
    "id": 128,
    "name": "Bad Boy Le Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Bad Boy Le Parfum.jpg",
    "file": "Bad Boy Le Parfum.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1890,
    "priceMayoreo": 1990
  },
  {
    "id": 129,
    "name": "Bad Boy",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Bad Boy.webp",
    "file": "Bad Boy.webp",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1690,
    "priceMayoreo": 1890
  },
  {
    "id": 130,
    "name": "Born In Roma Coral Fantasy (Uomo)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Born In Roma Coral Fantasy (Uomo).jpg",
    "file": "Born In Roma Coral Fantasy (Uomo).jpg",
    "brand": "Valentino",
    "priceMenudeo": 2080,
    "priceMayoreo": 2190
  },
  {
    "id": 131,
    "name": "Born In Roma EDT (Uomo)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Born In Roma EDT (Uomo).jpg",
    "file": "Born In Roma EDT (Uomo).jpg",
    "brand": "Valentino",
    "priceMenudeo": 2090,
    "priceMayoreo": 2290
  },
  {
    "id": 132,
    "name": "Born In Roma Extradose (Uomo)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Born In Roma Extradose (Uomo).jpg",
    "file": "Born In Roma Extradose (Uomo).jpg",
    "brand": "Valentino",
    "priceMenudeo": 3090,
    "priceMayoreo": 3290
  },
  {
    "id": 133,
    "name": "Born In Roma Green Stravaganza (Uomo)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Born In Roma Green Stravaganza (Uomo).png",
    "file": "Born In Roma Green Stravaganza (Uomo).png",
    "brand": "Valentino",
    "priceMenudeo": 2090,
    "priceMayoreo": 2190
  },
  {
    "id": 134,
    "name": "Born In Roma Intense (Uomo)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Born In Roma Intense (Uomo).jpg",
    "file": "Born In Roma Intense (Uomo).jpg",
    "brand": "Valentino",
    "priceMenudeo": 2690,
    "priceMayoreo": 2890
  },
  {
    "id": 135,
    "name": "Bottled Infinite",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Bottled Infinite.webp",
    "file": "Bottled Infinite.webp",
    "brand": "Hugo Boss",
    "priceMenudeo": 1050,
    "priceMayoreo": 1250
  },
  {
    "id": 136,
    "name": "Bottled",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Bottled.jpg",
    "file": "Bottled.jpg",
    "brand": "Hugo Boss",
    "priceMenudeo": 1060,
    "priceMayoreo": 1210
  },
  {
    "id": 137,
    "name": "CH Men",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/CH Men.webp",
    "file": "CH Men.webp",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1490,
    "priceMayoreo": 1590
  },
  {
    "id": 138,
    "name": "CK IN2U (H)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/CK IN2U (H).webp",
    "file": "CK IN2U (H).webp",
    "brand": "Calvin Klein",
    "priceMenudeo": 650,
    "priceMayoreo": 890
  },
  {
    "id": 139,
    "name": "CK One Shock (H)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/CK One Shock (H).webp",
    "file": "CK One Shock (H).webp",
    "brand": "Calvin Klein",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 140,
    "name": "Coach Blue",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Coach Blue.jpg",
    "file": "Coach Blue.jpg",
    "brand": "Coach",
    "priceMenudeo": 950,
    "priceMayoreo": 1090
  },
  {
    "id": 141,
    "name": "Coach for Men",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Coach for Men.webp",
    "file": "Coach for Men.webp",
    "brand": "Coach",
    "priceMenudeo": 950,
    "priceMayoreo": 1090
  },
  {
    "id": 142,
    "name": "Coach Platinum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Coach Platinum.jpg",
    "file": "Coach Platinum.jpg",
    "brand": "Coach",
    "priceMenudeo": 950,
    "priceMayoreo": 1090
  },
  {
    "id": 143,
    "name": "Dylan Blue",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Dylan Blue.webp",
    "file": "Dylan Blue.webp",
    "brand": "Versace",
    "priceMenudeo": 1190,
    "priceMayoreo": 1290
  },
  {
    "id": 144,
    "name": "Eau Fraîche",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Eau Fraîche.webp",
    "file": "Eau Fraîche.webp",
    "brand": "Versace",
    "priceMenudeo": 1090,
    "priceMayoreo": 1190
  },
  {
    "id": 145,
    "name": "Eros EDP",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Eros EDP.jpg",
    "file": "Eros EDP.jpg",
    "brand": "Versace",
    "priceMenudeo": 1390,
    "priceMayoreo": 1490
  },
  {
    "id": 146,
    "name": "Eros EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Eros EDT.png",
    "file": "Eros EDT.png",
    "brand": "Versace",
    "priceMenudeo": 1290,
    "priceMayoreo": 1390
  },
  {
    "id": 147,
    "name": "Eros Energy",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Eros Energy.jpg",
    "file": "Eros Energy.jpg",
    "brand": "Versace",
    "priceMenudeo": 1690,
    "priceMayoreo": 1990
  },
  {
    "id": 148,
    "name": "Eros Flame",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Eros Flame.jpg",
    "file": "Eros Flame.jpg",
    "brand": "Versace",
    "priceMenudeo": 1390,
    "priceMayoreo": 1590
  },
  {
    "id": 149,
    "name": "Eros Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Eros Parfum.webp",
    "file": "Eros Parfum.webp",
    "brand": "Versace",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 150,
    "name": "Eternity for Men",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Eternity for Men.webp",
    "file": "Eternity for Men.webp",
    "brand": "Calvin Klein",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 151,
    "name": "Explorer Platinum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Explorer Platinum.webp",
    "file": "Explorer Platinum.webp",
    "brand": "Montblanc",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 152,
    "name": "Explorer Ultra Blue",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Explorer Ultra Blue.webp",
    "file": "Explorer Ultra Blue.webp",
    "brand": "Montblanc",
    "priceMenudeo": 890,
    "priceMayoreo": 950
  },
  {
    "id": 153,
    "name": "Explorer",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Explorer.webp",
    "file": "Explorer.webp",
    "brand": "Montblanc",
    "priceMenudeo": 990,
    "priceMayoreo": 1120
  },
  {
    "id": 154,
    "name": "Fahrenheit",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Fahrenheit.jpg",
    "file": "Fahrenheit.jpg",
    "brand": "Dior",
    "priceMenudeo": 1890,
    "priceMayoreo": 1990
  },
  {
    "id": 155,
    "name": "Halloween Man Mistery",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Halloween Man Mistery.webp",
    "file": "Halloween Man Mistery.webp",
    "brand": "Halloween",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 156,
    "name": "Halloween Man Rock On",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Halloween Man Rock On.webp",
    "file": "Halloween Man Rock On.webp",
    "brand": "Halloween",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 157,
    "name": "Halloween Man X",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Halloween Man X.webp",
    "file": "Halloween Man X.webp",
    "brand": "Halloween",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 158,
    "name": "Halloween Man",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Halloween Man.webp",
    "file": "Halloween Man.webp",
    "brand": "Halloween",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 159,
    "name": "Hugo In Motion",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Hugo In Motion.jpg",
    "file": "Hugo In Motion.jpg",
    "brand": "Hugo Boss",
    "priceMenudeo": 620,
    "priceMayoreo": 760
  },
  {
    "id": 160,
    "name": "Hugo Just Different",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Hugo Just Different.webp",
    "file": "Hugo Just Different.webp",
    "brand": "Hugo Boss",
    "priceMenudeo": 890,
    "priceMayoreo": 990
  },
  {
    "id": 161,
    "name": "Hugo XY",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Hugo XY.webp",
    "file": "Hugo XY.webp",
    "brand": "Hugo Boss",
    "priceMenudeo": 650,
    "priceMayoreo": 980
  },
  {
    "id": 162,
    "name": "Hugo",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Hugo.png",
    "file": "Hugo.png",
    "brand": "Hugo Boss",
    "priceMenudeo": 890,
    "priceMayoreo": 990
  },
  {
    "id": 163,
    "name": "Impact Intense",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Impact Intense.webp",
    "file": "Impact Intense.webp",
    "brand": "Tommy Hilfiger",
    "priceMenudeo": 1090,
    "priceMayoreo": 1190
  },
  {
    "id": 164,
    "name": "Impact Spark",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Impact Spark.jpg",
    "file": "Impact Spark.jpg",
    "brand": "Tommy Hilfiger",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 165,
    "name": "Impact",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Impact.webp",
    "file": "Impact.webp",
    "brand": "Tommy Hilfiger",
    "priceMenudeo": 1090,
    "priceMayoreo": 1190
  },
  {
    "id": 166,
    "name": "Invictus Aqua",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Invictus Aqua.jpg",
    "file": "Invictus Aqua.jpg",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1590,
    "priceMayoreo": 1890
  },
  {
    "id": 167,
    "name": "Invictus Victory Elixir",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Invictus Victory Elixir.jpg",
    "file": "Invictus Victory Elixir.jpg",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1890,
    "priceMayoreo": 1990
  },
  {
    "id": 168,
    "name": "Invictus Victory",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Invictus Victory.webp",
    "file": "Invictus Victory.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1790,
    "priceMayoreo": 1990
  },
  {
    "id": 169,
    "name": "Invictus",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Invictus.webp",
    "file": "Invictus.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1490,
    "priceMayoreo": 1590
  },
  {
    "id": 170,
    "name": "K EDP",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/K EDP.jpg",
    "file": "K EDP.jpg",
    "brand": "Dolce & Gabbana",
    "priceMenudeo": 1370,
    "priceMayoreo": 1490
  },
  {
    "id": 171,
    "name": "K EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/K EDT.webp",
    "file": "K EDT.webp",
    "brand": "Dolce & Gabbana",
    "priceMenudeo": 1220,
    "priceMayoreo": 1390
  },
  {
    "id": 172,
    "name": "Le Beau EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Le Beau EDT.webp",
    "file": "Le Beau EDT.webp",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 1690,
    "priceMayoreo": 1890
  },
  {
    "id": 173,
    "name": "Le Beau Le Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Le Beau Le Parfum.jpg",
    "file": "Le Beau Le Parfum.jpg",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 2390,
    "priceMayoreo": 2590
  },
  {
    "id": 174,
    "name": "Le Beau Paradise Garden",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Le Beau Paradise Garden.webp",
    "file": "Le Beau Paradise Garden.webp",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 1990,
    "priceMayoreo": 2390
  },
  {
    "id": 175,
    "name": "Le Male EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Le Male EDT.webp",
    "file": "Le Male EDT.webp",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 1690,
    "priceMayoreo": 1890
  },
  {
    "id": 176,
    "name": "Le Male Elixir Absolu",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Le Male Elixir Absolu.jpg",
    "file": "Le Male Elixir Absolu.jpg",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 2090,
    "priceMayoreo": 2390
  },
  {
    "id": 177,
    "name": "Le Male Elixir",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Le Male Elixir.jpg",
    "file": "Le Male Elixir.jpg",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 2090,
    "priceMayoreo": 2390
  },
  {
    "id": 178,
    "name": "Le Male Le Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Le Male Le Parfum.jpg",
    "file": "Le Male Le Parfum.jpg",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 2090,
    "priceMayoreo": 2390
  },
  {
    "id": 179,
    "name": "Legend Red",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Legend Red.jpg",
    "file": "Legend Red.jpg",
    "brand": "Montblanc",
    "priceMenudeo": 890,
    "priceMayoreo": 1090
  },
  {
    "id": 180,
    "name": "Legend Spirit",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Legend Spirit.webp",
    "file": "Legend Spirit.webp",
    "brand": "Montblanc",
    "priceMenudeo": 860,
    "priceMayoreo": 990
  },
  {
    "id": 181,
    "name": "Legend",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Legend.webp",
    "file": "Legend.webp",
    "brand": "Montblanc",
    "priceMenudeo": 880,
    "priceMayoreo": 990
  },
  {
    "id": 182,
    "name": "Light Blue (H)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Light Blue (H).webp",
    "file": "Light Blue (H).webp",
    "brand": "Dolce & Gabbana",
    "priceMenudeo": 1040,
    "priceMayoreo": 1190
  },
  {
    "id": 183,
    "name": "MYSLF",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/MYSLF.png",
    "file": "MYSLF.png",
    "brand": "YSL",
    "priceMenudeo": 2190,
    "priceMayoreo": 2390
  },
  {
    "id": 184,
    "name": "Nautica Blue",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Nautica Blue.webp",
    "file": "Nautica Blue.webp",
    "brand": "Nautica",
    "priceMenudeo": 390,
    "priceMayoreo": 490
  },
  {
    "id": 185,
    "name": "Nautica Classic",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Nautica Classic.webp",
    "file": "Nautica Classic.webp",
    "brand": "Nautica",
    "priceMenudeo": 390,
    "priceMayoreo": 490
  },
  {
    "id": 186,
    "name": "Nautica Sport",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Nautica Sport.webp",
    "file": "Nautica Sport.webp",
    "brand": "Nautica",
    "priceMenudeo": 390,
    "priceMayoreo": 490
  },
  {
    "id": 187,
    "name": "Nautica Voyage",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Nautica Voyage.webp",
    "file": "Nautica Voyage.webp",
    "brand": "Nautica",
    "priceMenudeo": 360,
    "priceMayoreo": 390
  },
  {
    "id": 188,
    "name": "One Million Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/One Million Parfum.webp",
    "file": "One Million Parfum.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1890,
    "priceMayoreo": 1990
  },
  {
    "id": 189,
    "name": "One Million Royal",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/One Million Royal.webp",
    "file": "One Million Royal.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1990,
    "priceMayoreo": 2090
  },
  {
    "id": 190,
    "name": "One Million",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/One Million.webp",
    "file": "One Million.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1490,
    "priceMayoreo": 1590
  },
  {
    "id": 191,
    "name": "Paris Hilton (H)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Paris Hilton (H).webp",
    "file": "Paris Hilton (H).webp",
    "brand": "Paris Hilton",
    "priceMenudeo": 660,
    "priceMayoreo": 790
  },
  {
    "id": 192,
    "name": "Phantom Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Phantom Parfum.webp",
    "file": "Phantom Parfum.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1890,
    "priceMayoreo": 2090
  },
  {
    "id": 193,
    "name": "Phantom",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Phantom.jpg",
    "file": "Phantom.jpg",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 194,
    "name": "Polo Black",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Polo Black.jpg",
    "file": "Polo Black.jpg",
    "brand": "Ralph Lauren",
    "priceMenudeo": 1290,
    "priceMayoreo": 1490
  },
  {
    "id": 195,
    "name": "Polo Blue",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Polo Blue.webp",
    "file": "Polo Blue.webp",
    "brand": "Ralph Lauren",
    "priceMenudeo": 1290,
    "priceMayoreo": 1490
  },
  {
    "id": 196,
    "name": "Polo Red Rush",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Polo Red Rush.jpg",
    "file": "Polo Red Rush.jpg",
    "brand": "Ralph Lauren",
    "priceMenudeo": 1290,
    "priceMayoreo": 1420
  },
  {
    "id": 197,
    "name": "Polo Red",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Polo Red.jpg",
    "file": "Polo Red.jpg",
    "brand": "Ralph Lauren",
    "priceMenudeo": 1290,
    "priceMayoreo": 1490
  },
  {
    "id": 198,
    "name": "Pour Homme (Dolce & Gabbana)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Pour Homme (Dolce & Gabbana).webp",
    "file": "Pour Homme (Dolce & Gabbana).webp",
    "brand": "Dolce & Gabbana",
    "priceMenudeo": 990,
    "priceMayoreo": 1090
  },
  {
    "id": 199,
    "name": "Pour Homme (Versace)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Pour Homme (Versace).webp",
    "file": "Pour Homme (Versace).webp",
    "brand": "Versace",
    "priceMenudeo": 1090,
    "priceMayoreo": 1290
  },
  {
    "id": 200,
    "name": "Pure XS",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Pure XS.webp",
    "file": "Pure XS.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 201,
    "name": "Sauvage EDP",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Sauvage EDP.webp",
    "file": "Sauvage EDP.webp",
    "brand": "Dior",
    "priceMenudeo": 2590,
    "priceMayoreo": 2790
  },
  {
    "id": 202,
    "name": "Sauvage EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Sauvage EDT.webp",
    "file": "Sauvage EDT.webp",
    "brand": "Dior",
    "priceMenudeo": 2390,
    "priceMayoreo": 2490
  },
  {
    "id": 203,
    "name": "Sauvage Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Sauvage Parfum.jpg",
    "file": "Sauvage Parfum.jpg",
    "brand": "Dior",
    "priceMenudeo": 2890,
    "priceMayoreo": 2990
  },
  {
    "id": 204,
    "name": "Starwalker",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Starwalker.webp",
    "file": "Starwalker.webp",
    "brand": "Montblanc",
    "priceMenudeo": 620,
    "priceMayoreo": 770
  },
  {
    "id": 205,
    "name": "Stronger With You Absolutely",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Stronger With You Absolutely.jpg",
    "file": "Stronger With You Absolutely.jpg",
    "brand": "Armani",
    "priceMenudeo": 2150,
    "priceMayoreo": 2290
  },
  {
    "id": 206,
    "name": "Stronger With You EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Stronger With You EDT.jpg",
    "file": "Stronger With You EDT.jpg",
    "brand": "Armani",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 207,
    "name": "Stronger With You Intensely",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Stronger With You Intensely.jpg",
    "file": "Stronger With You Intensely.jpg",
    "brand": "Armani",
    "priceMenudeo": 1990,
    "priceMayoreo": 2290
  },
  {
    "id": 208,
    "name": "Stronger With You Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Stronger With You Parfum.jpg",
    "file": "Stronger With You Parfum.jpg",
    "brand": "Armani",
    "priceMenudeo": 2290,
    "priceMayoreo": 2590
  },
  {
    "id": 209,
    "name": "The Most Wanted EDP",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/The Most Wanted EDP.webp",
    "file": "The Most Wanted EDP.webp",
    "brand": "Azzaro",
    "priceMenudeo": 1290,
    "priceMayoreo": 1590
  },
  {
    "id": 210,
    "name": "The Most Wanted EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/The Most Wanted EDT.jpg",
    "file": "The Most Wanted EDT.jpg",
    "brand": "Azzaro",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 211,
    "name": "The Most Wanted Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/The Most Wanted Parfum.webp",
    "file": "The Most Wanted Parfum.webp",
    "brand": "Azzaro",
    "priceMenudeo": 1590,
    "priceMayoreo": 1890
  },
  {
    "id": 212,
    "name": "The Scent",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/The Scent.webp",
    "file": "The Scent.webp",
    "brand": "Hugo Boss",
    "priceMenudeo": 1390,
    "priceMayoreo": 1490
  },
  {
    "id": 213,
    "name": "Tommy (H)",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Tommy (H).webp",
    "file": "Tommy (H).webp",
    "brand": "Tommy Hilfiger",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 214,
    "name": "Toy Boy",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Toy Boy.jpg",
    "file": "Toy Boy.jpg",
    "brand": "Moschino",
    "priceMenudeo": 1190,
    "priceMayoreo": 1290
  },
  {
    "id": 215,
    "name": "Ultra Male",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Ultra Male.webp",
    "file": "Ultra Male.webp",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 1790,
    "priceMayoreo": 1890
  },
  {
    "id": 216,
    "name": "Wanted by Night",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Wanted by Night.jpg",
    "file": "Wanted by Night.jpg",
    "brand": "Azzaro",
    "priceMenudeo": 1090,
    "priceMayoreo": 1190
  },
  {
    "id": 217,
    "name": "Wanted EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Wanted EDT.webp",
    "file": "Wanted EDT.webp",
    "brand": "Azzaro",
    "priceMenudeo": 940,
    "priceMayoreo": 990
  },
  {
    "id": 218,
    "name": "Y EDP",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Y EDP.jpg",
    "file": "Y EDP.jpg",
    "brand": "YSL",
    "priceMenudeo": 2090,
    "priceMayoreo": 2290
  },
  {
    "id": 219,
    "name": "Y EDT",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Y EDT.jpg",
    "file": "Y EDT.jpg",
    "brand": "YSL",
    "priceMenudeo": 1955,
    "priceMayoreo": 2090
  },
  {
    "id": 220,
    "name": "Y Intense",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Y Intense.jpg",
    "file": "Y Intense.jpg",
    "brand": "YSL",
    "priceMenudeo": 2190,
    "priceMayoreo": 2390
  },
  {
    "id": 221,
    "name": "Y Le Parfum",
    "gender": "Hombre",
    "line": "Disenador",
    "image": "../Hombre/Disenador/Y Le Parfum.jpg",
    "file": "Y Le Parfum.jpg",
    "brand": "YSL",
    "priceMenudeo": 2290,
    "priceMayoreo": 2390
  },
  {
    "id": 222,
    "name": "9PM Pour Femme",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/9PM Pour Femme.webp",
    "file": "9PM Pour Femme.webp",
    "brand": "Afnan",
    "priceMenudeo": 680,
    "priceMayoreo": 780
  },
  {
    "id": 223,
    "name": "Bouje",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Bouje.jpg",
    "file": "Bouje.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 224,
    "name": "Candee",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Candee.jpg",
    "file": "Candee.jpg",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 890
  },
  {
    "id": 225,
    "name": "Club de Nuit Woman",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Club de Nuit Woman.webp",
    "file": "Club de Nuit Woman.webp",
    "brand": "Armaf",
    "priceMenudeo": 590,
    "priceMayoreo": 740
  },
  {
    "id": 226,
    "name": "Emaan",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Emaan.jpg",
    "file": "Emaan.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 227,
    "name": "Goddess",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Goddess.jpg",
    "file": "Goddess.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 228,
    "name": "Hawas for Her",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Hawas for Her.jpg",
    "file": "Hawas for Her.jpg",
    "brand": "Rasasi",
    "priceMenudeo": 590,
    "priceMayoreo": 750
  },
  {
    "id": 229,
    "name": "Haya",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Haya.png",
    "file": "Haya.png",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 230,
    "name": "Maleka",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Maleka.jpg",
    "file": "Maleka.jpg",
    "brand": "Armaf",
    "priceMenudeo": 890,
    "priceMayoreo": 1030
  },
  {
    "id": 231,
    "name": "Mayar Natural",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Mayar Natural.jpg",
    "file": "Mayar Natural.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 790
  },
  {
    "id": 232,
    "name": "Noble Blush",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Noble Blush.webp",
    "file": "Noble Blush.webp",
    "brand": "Lattafa",
    "priceMenudeo": 590,
    "priceMayoreo": 750
  },
  {
    "id": 233,
    "name": "Queen",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Queen.jpg",
    "file": "Queen.jpg",
    "brand": "Jo Milano",
    "priceMenudeo": 1550,
    "priceMayoreo": 1690
  },
  {
    "id": 234,
    "name": "Rome Pour Femme",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Rome Pour Femme.jpg",
    "file": "Rome Pour Femme.jpg",
    "brand": "MP",
    "priceMenudeo": 760,
    "priceMayoreo": 990
  },
  {
    "id": 235,
    "name": "Rose",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Rose.jpg",
    "file": "Rose.jpg",
    "brand": "Bharara",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 236,
    "name": "Untold",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Untold.png",
    "file": "Untold.png",
    "brand": "Armaf",
    "priceMenudeo": 790,
    "priceMayoreo": 990
  },
  {
    "id": 237,
    "name": "Yara Candy",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Yara Candy.jpg",
    "file": "Yara Candy.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 540,
    "priceMayoreo": 690
  },
  {
    "id": 238,
    "name": "Yara Moi",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Yara Moi.webp",
    "file": "Yara Moi.webp",
    "brand": "Lattafa",
    "priceMenudeo": 530,
    "priceMayoreo": 690
  },
  {
    "id": 239,
    "name": "Yara Tous",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Yara Tous.webp",
    "file": "Yara Tous.webp",
    "brand": "Lattafa",
    "priceMenudeo": 520,
    "priceMayoreo": 690
  },
  {
    "id": 240,
    "name": "Yara",
    "gender": "Mujer",
    "line": "Arabes",
    "image": "../Mujer/Arabes/Yara.jpg",
    "file": "Yara.jpg",
    "brand": "Lattafa",
    "priceMenudeo": 510,
    "priceMayoreo": 690
  },
  {
    "id": 241,
    "name": "212 Heroes (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/212 Heroes (M).webp",
    "file": "212 Heroes (M).webp",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1690,
    "priceMayoreo": 1890
  },
  {
    "id": 242,
    "name": "212 Sexy",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/212 Sexy.jpg",
    "file": "212 Sexy.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1490,
    "priceMayoreo": 1590
  },
  {
    "id": 243,
    "name": "212",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/212.webp",
    "file": "212.webp",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1490,
    "priceMayoreo": 1590
  },
  {
    "id": 244,
    "name": "360 (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/360 (M).jpg",
    "file": "360 (M).jpg",
    "brand": "Perry Ellis",
    "priceMenudeo": 560,
    "priceMayoreo": 690
  },
  {
    "id": 245,
    "name": "360 Coral",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/360 Coral.png",
    "file": "360 Coral.png",
    "brand": "Perry Ellis",
    "priceMenudeo": 560,
    "priceMayoreo": 690
  },
  {
    "id": 246,
    "name": "360 Purple",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/360 Purple.png",
    "file": "360 Purple.png",
    "brand": "Perry Ellis",
    "priceMenudeo": 560,
    "priceMayoreo": 690
  },
  {
    "id": 247,
    "name": "Amor Amor",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Amor Amor.webp",
    "file": "Amor Amor.webp",
    "brand": "Cacharel",
    "priceMenudeo": 690,
    "priceMayoreo": 890
  },
  {
    "id": 248,
    "name": "Anais Anais",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Anais Anais.webp",
    "file": "Anais Anais.webp",
    "brand": "Cacharel",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 249,
    "name": "Ari by Ari",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Ari by Ari.webp",
    "file": "Ari by Ari.webp",
    "brand": "Ariana Grande",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 250,
    "name": "Black Opium",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Black Opium.jpg",
    "file": "Black Opium.jpg",
    "brand": "YSL",
    "priceMenudeo": 2190,
    "priceMayoreo": 2490
  },
  {
    "id": 251,
    "name": "Blooming Bouquet",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Blooming Bouquet.jpg",
    "file": "Blooming Bouquet.jpg",
    "brand": "Dior",
    "priceMenudeo": 2390,
    "priceMayoreo": 2590
  },
  {
    "id": 252,
    "name": "Born In Roma Coral Fantasy (Donna)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Born In Roma Coral Fantasy (Donna).jpg",
    "file": "Born In Roma Coral Fantasy (Donna).jpg",
    "brand": "Valentino",
    "priceMenudeo": 2460,
    "priceMayoreo": 2590
  },
  {
    "id": 253,
    "name": "Born In Roma EDP (Donna)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Born In Roma EDP (Donna).jpg",
    "file": "Born In Roma EDP (Donna).jpg",
    "brand": "Valentino",
    "priceMenudeo": 2590,
    "priceMayoreo": 2750
  },
  {
    "id": 254,
    "name": "Born In Roma Extradose (Donna)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Born In Roma Extradose (Donna).jpg",
    "file": "Born In Roma Extradose (Donna).jpg",
    "brand": "Valentino",
    "priceMenudeo": 3090,
    "priceMayoreo": 3290
  },
  {
    "id": 255,
    "name": "Born In Roma Green Stravaganza (Donna)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Born In Roma Green Stravaganza (Donna).jpg",
    "file": "Born In Roma Green Stravaganza (Donna).jpg",
    "brand": "Valentino",
    "priceMenudeo": 2590,
    "priceMayoreo": 2790
  },
  {
    "id": 256,
    "name": "Born In Roma Intense (Donna)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Born In Roma Intense (Donna).webp",
    "file": "Born In Roma Intense (Donna).webp",
    "brand": "Valentino",
    "priceMenudeo": 2790,
    "priceMayoreo": 2890
  },
  {
    "id": 257,
    "name": "Bright Crystal Absolu",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Bright Crystal Absolu.png",
    "file": "Bright Crystal Absolu.png",
    "brand": "Versace",
    "priceMenudeo": 1290,
    "priceMayoreo": 1490
  },
  {
    "id": 258,
    "name": "Bright Crystal",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Bright Crystal.jpg",
    "file": "Bright Crystal.jpg",
    "brand": "Versace",
    "priceMenudeo": 1190,
    "priceMayoreo": 1390
  },
  {
    "id": 259,
    "name": "Can Can",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Can Can.png",
    "file": "Can Can.png",
    "brand": "Paris Hilton",
    "priceMenudeo": 660,
    "priceMayoreo": 790
  },
  {
    "id": 260,
    "name": "CH Woman",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/CH Woman.webp",
    "file": "CH Woman.webp",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 261,
    "name": "CK IN2U (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/CK IN2U (M).webp",
    "file": "CK IN2U (M).webp",
    "brand": "Calvin Klein",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 262,
    "name": "CK One Shock (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/CK One Shock (M).webp",
    "file": "CK One Shock (M).webp",
    "brand": "Calvin Klein",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 263,
    "name": "Cloud Pink",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Cloud Pink.webp",
    "file": "Cloud Pink.webp",
    "brand": "Ariana Grande",
    "priceMenudeo": 1390,
    "priceMayoreo": 1490
  },
  {
    "id": 264,
    "name": "Cloud",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Cloud.webp",
    "file": "Cloud.webp",
    "brand": "Ariana Grande",
    "priceMenudeo": 1090,
    "priceMayoreo": 1290
  },
  {
    "id": 265,
    "name": "Coach Dreams Sunset",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Coach Dreams Sunset.png",
    "file": "Coach Dreams Sunset.png",
    "brand": "Coach",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 266,
    "name": "Coach Dreams",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Coach Dreams.png",
    "file": "Coach Dreams.png",
    "brand": "Coach",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 267,
    "name": "Coach EDP",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Coach EDP.png",
    "file": "Coach EDP.png",
    "brand": "Coach",
    "priceMenudeo": 940,
    "priceMayoreo": 1090
  },
  {
    "id": 268,
    "name": "Coach Floral",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Coach Floral.png",
    "file": "Coach Floral.png",
    "brand": "Coach",
    "priceMenudeo": 990,
    "priceMayoreo": 1090
  },
  {
    "id": 269,
    "name": "Coach Wild Rose",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Coach Wild Rose.jpg",
    "file": "Coach Wild Rose.jpg",
    "brand": "Coach",
    "priceMenudeo": 960,
    "priceMayoreo": 1090
  },
  {
    "id": 270,
    "name": "Dylan Blue (Pour Femme)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Dylan Blue (Pour Femme).webp",
    "file": "Dylan Blue (Pour Femme).webp",
    "brand": "Versace",
    "priceMenudeo": 1190,
    "priceMayoreo": 1290
  },
  {
    "id": 271,
    "name": "Dylan Purple",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Dylan Purple.jpg",
    "file": "Dylan Purple.jpg",
    "brand": "Versace",
    "priceMenudeo": 1290,
    "priceMayoreo": 1390
  },
  {
    "id": 272,
    "name": "Dylan Turquoise",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Dylan Turquoise.webp",
    "file": "Dylan Turquoise.webp",
    "brand": "Versace",
    "priceMenudeo": 1190,
    "priceMayoreo": 1360
  },
  {
    "id": 273,
    "name": "Eternity",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Eternity.webp",
    "file": "Eternity.webp",
    "brand": "Calvin Klein",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 274,
    "name": "Fame Blooming Pink",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Fame Blooming Pink.jpg",
    "file": "Fame Blooming Pink.jpg",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 275,
    "name": "Fame",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Fame.webp",
    "file": "Fame.webp",
    "brand": "Paco Rabanne",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 276,
    "name": "Fresh Gold",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Fresh Gold.jpg",
    "file": "Fresh Gold.jpg",
    "brand": "Moschino",
    "priceMenudeo": 920,
    "priceMayoreo": 1090
  },
  {
    "id": 277,
    "name": "Fresh Pink",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Fresh Pink.jpg",
    "file": "Fresh Pink.jpg",
    "brand": "Moschino",
    "priceMenudeo": 910,
    "priceMayoreo": 1090
  },
  {
    "id": 278,
    "name": "Fresh",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Fresh.jpg",
    "file": "Fresh.jpg",
    "brand": "Moschino",
    "priceMenudeo": 790,
    "priceMayoreo": 950
  },
  {
    "id": 279,
    "name": "Funny",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Funny.webp",
    "file": "Funny.webp",
    "brand": "Moschino",
    "priceMenudeo": 710,
    "priceMayoreo": 850
  },
  {
    "id": 280,
    "name": "God is a Woman",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/God is a Woman.webp",
    "file": "God is a Woman.webp",
    "brand": "Ariana Grande",
    "priceMenudeo": 880,
    "priceMayoreo": 1090
  },
  {
    "id": 281,
    "name": "Gold Rush",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Gold Rush.webp",
    "file": "Gold Rush.webp",
    "brand": "Paris Hilton",
    "priceMenudeo": 660,
    "priceMayoreo": 790
  },
  {
    "id": 282,
    "name": "Good Girl",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Good Girl.jpg",
    "file": "Good Girl.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 1890,
    "priceMayoreo": 2090
  },
  {
    "id": 283,
    "name": "Halloween (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Halloween (M).webp",
    "file": "Halloween (M).webp",
    "brand": "Halloween",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 284,
    "name": "Heiress",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Heiress.jpg",
    "file": "Heiress.jpg",
    "brand": "Paris Hilton",
    "priceMenudeo": 660,
    "priceMayoreo": 790
  },
  {
    "id": 285,
    "name": "Hypnôse",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Hypnôse.jpg",
    "file": "Hypnôse.jpg",
    "brand": "Lancôme",
    "priceMenudeo": 1390,
    "priceMayoreo": 1490
  },
  {
    "id": 286,
    "name": "I Love Love",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/I Love Love.jpg",
    "file": "I Love Love.jpg",
    "brand": "Moschino",
    "priceMenudeo": 710,
    "priceMayoreo": 890
  },
  {
    "id": 287,
    "name": "Idôle",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Idôle.jpg",
    "file": "Idôle.jpg",
    "brand": "Lancôme",
    "priceMenudeo": 1990,
    "priceMayoreo": 2190
  },
  {
    "id": 288,
    "name": "J'adore",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/J'adore.jpg",
    "file": "J'adore.jpg",
    "brand": "Dior",
    "priceMenudeo": 2390,
    "priceMayoreo": 2490
  },
  {
    "id": 289,
    "name": "La Vie Est Belle Intensément",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/La Vie Est Belle Intensément.png",
    "file": "La Vie Est Belle Intensément.png",
    "brand": "Lancôme",
    "priceMenudeo": 1950,
    "priceMayoreo": 2050
  },
  {
    "id": 290,
    "name": "La Vie Est Belle L'Éclat",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/La Vie Est Belle L'Éclat.jpg",
    "file": "La Vie Est Belle L'Éclat.jpg",
    "brand": "Lancôme",
    "priceMenudeo": 1890,
    "priceMayoreo": 1990
  },
  {
    "id": 291,
    "name": "La Vie Est Belle",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/La Vie Est Belle.jpg",
    "file": "La Vie Est Belle.jpg",
    "brand": "Lancôme",
    "priceMenudeo": 1890,
    "priceMayoreo": 1990
  },
  {
    "id": 292,
    "name": "Libre EDP",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Libre EDP.jpg",
    "file": "Libre EDP.jpg",
    "brand": "YSL",
    "priceMenudeo": 2290,
    "priceMayoreo": 2450
  },
  {
    "id": 293,
    "name": "Libre EDT",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Libre EDT.jpg",
    "file": "Libre EDT.jpg",
    "brand": "YSL",
    "priceMenudeo": 2090,
    "priceMayoreo": 2290
  },
  {
    "id": 294,
    "name": "Light Blue (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Light Blue (M).webp",
    "file": "Light Blue (M).webp",
    "brand": "Dolce & Gabbana",
    "priceMenudeo": 1180,
    "priceMayoreo": 1290
  },
  {
    "id": 295,
    "name": "Meow",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Meow.jpg",
    "file": "Meow.jpg",
    "brand": "Katy Perry",
    "priceMenudeo": 540,
    "priceMayoreo": 690
  },
  {
    "id": 296,
    "name": "Miss Dior",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Miss Dior.jpg",
    "file": "Miss Dior.jpg",
    "brand": "Dior",
    "priceMenudeo": 2790,
    "priceMayoreo": 2890
  },
  {
    "id": 297,
    "name": "Mod Blush",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Mod Blush.jpg",
    "file": "Mod Blush.jpg",
    "brand": "Ariana Grande",
    "priceMenudeo": 1190,
    "priceMayoreo": 1240
  },
  {
    "id": 298,
    "name": "Mod Vainilla",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Mod Vainilla.jpg",
    "file": "Mod Vainilla.jpg",
    "brand": "Ariana Grande",
    "priceMenudeo": 1090,
    "priceMayoreo": 1190
  },
  {
    "id": 299,
    "name": "Mon Paris",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Mon Paris.webp",
    "file": "Mon Paris.webp",
    "brand": "YSL",
    "priceMenudeo": 2090,
    "priceMayoreo": 2290
  },
  {
    "id": 300,
    "name": "Moonlight",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Moonlight.webp",
    "file": "Moonlight.webp",
    "brand": "Ariana Grande",
    "priceMenudeo": 790,
    "priceMayoreo": 890
  },
  {
    "id": 301,
    "name": "Now (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Now (M).webp",
    "file": "Now (M).webp",
    "brand": "Tommy Hilfiger",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 302,
    "name": "Paris Hilton (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Paris Hilton (M).webp",
    "file": "Paris Hilton (M).webp",
    "brand": "Paris Hilton",
    "priceMenudeo": 660,
    "priceMayoreo": 790
  },
  {
    "id": 303,
    "name": "Poeme",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Poeme.jpg",
    "file": "Poeme.jpg",
    "brand": "Lancôme",
    "priceMenudeo": 1690,
    "priceMayoreo": 1790
  },
  {
    "id": 304,
    "name": "Pour Femme",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Pour Femme.webp",
    "file": "Pour Femme.webp",
    "brand": "Versace",
    "priceMenudeo": 1290,
    "priceMayoreo": 1490
  },
  {
    "id": 305,
    "name": "Purr",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Purr.webp",
    "file": "Purr.webp",
    "brand": "Katy Perry",
    "priceMenudeo": 540,
    "priceMayoreo": 690
  },
  {
    "id": 306,
    "name": "Q",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Q.jpg",
    "file": "Q.jpg",
    "brand": "Dolce & Gabbana",
    "priceMenudeo": 1430,
    "priceMayoreo": 1550
  },
  {
    "id": 307,
    "name": "R.E.M",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/R.E.M.webp",
    "file": "R.E.M.webp",
    "brand": "Ariana Grande",
    "priceMenudeo": 990,
    "priceMayoreo": 1090
  },
  {
    "id": 308,
    "name": "Roses N Roses",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Roses N Roses.jpg",
    "file": "Roses N Roses.jpg",
    "brand": "Dior",
    "priceMenudeo": 2490,
    "priceMayoreo": 2590
  },
  {
    "id": 309,
    "name": "Scandal Absolu",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Scandal Absolu.jpg",
    "file": "Scandal Absolu.jpg",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 2190,
    "priceMayoreo": 2390
  },
  {
    "id": 310,
    "name": "Scandal EDT",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Scandal EDT.webp",
    "file": "Scandal EDT.webp",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 1790,
    "priceMayoreo": 1890
  },
  {
    "id": 311,
    "name": "Scandal Le Parfum",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Scandal Le Parfum.webp",
    "file": "Scandal Le Parfum.webp",
    "brand": "Jean Paul Gaultier",
    "priceMenudeo": 1890,
    "priceMayoreo": 2090
  },
  {
    "id": 312,
    "name": "Thank U Next",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Thank U Next.webp",
    "file": "Thank U Next.webp",
    "brand": "Ariana Grande",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 313,
    "name": "Tommy (M)",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Tommy (M).webp",
    "file": "Tommy (M).webp",
    "brand": "Tommy Hilfiger",
    "priceMenudeo": 690,
    "priceMayoreo": 790
  },
  {
    "id": 314,
    "name": "Toy 2",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Toy 2.jpg",
    "file": "Toy 2.jpg",
    "brand": "Moschino",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 315,
    "name": "Toy Bubble Gum",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Toy Bubble Gum.jpg",
    "file": "Toy Bubble Gum.jpg",
    "brand": "Moschino",
    "priceMenudeo": 990,
    "priceMayoreo": 1190
  },
  {
    "id": 316,
    "name": "Toy Pearl",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Toy Pearl.jpg",
    "file": "Toy Pearl.jpg",
    "brand": "Moschino",
    "priceMenudeo": 1490,
    "priceMayoreo": 1590
  },
  {
    "id": 317,
    "name": "Trésor Midnight Rose",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Trésor Midnight Rose.jpg",
    "file": "Trésor Midnight Rose.jpg",
    "brand": "Lancôme",
    "priceMenudeo": 1990,
    "priceMayoreo": 2190
  },
  {
    "id": 318,
    "name": "Very Good Girl",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Very Good Girl.jpg",
    "file": "Very Good Girl.jpg",
    "brand": "Carolina Herrera",
    "priceMenudeo": 2190,
    "priceMayoreo": 2390
  },
  {
    "id": 319,
    "name": "Yellow Diamond",
    "gender": "Mujer",
    "line": "Disenador",
    "image": "../Mujer/Disenador/Yellow Diamond.png",
    "file": "Yellow Diamond.png",
    "brand": "Versace",
    "priceMenudeo": 1190,
    "priceMayoreo": 1290
  }
];
